name: Log ISS Location Data Daily

on:
  schedule:
    - cron: "0 12 * * *"  # runs every day at 12:00 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Python packages
        id: prime-cache-66e41c0
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-66e41c0

      - name: Show cache result
        run: echo "Cache hit? ${{ steps.prime-cache-66e41c0.outputs.cache-hit }}"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python dependencies
        run: uv run --with pip install requests

      - name: Fetch ISS location data
        run: |
          uv run --with requests python << 'EOF'
          import requests
          data = requests.get('http://api.open-notify.org/iss-now.json').text
          with open('iss-location.jsonl', 'a') as f:
              f.write(data + '\n')
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add iss-location.jsonl
          git commit -m "Update ISS position data [skip ci]" || exit 0
          git push
