name: Simple Test Action

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3000515@ds.study.iitm.ac.in
        run: echo "Hello, world!"
